# Generated by Django 5.1.1 on 2024-09-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0003_alter_guild_options_remove_wizard_guild_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('cost', models.TextField(verbose_name='Стоимость')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.customer')),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.guild')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Wizard_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.order')),
                ('wizard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.wizard')),
            ],
            options={
                'verbose_name': 'Волшебник_Заказ',
                'verbose_name_plural': 'Волшебник_Заказ',
            },
        ),
    ]
