# Generated by Django 5.1.1 on 2024-11-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0006_order_status_team_order_team_wizard_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.team'),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.team'),
        ),
    ]
