# Generated by Django 5.1.1 on 2024-11-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0009_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wizard_Order',
        ),
    ]
