# Generated by Django 5.1.1 on 2024-12-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0011_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserMine',
        ),
    ]
