# Generated by Django 5.1.1 on 2024-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0016_alter_customer_email_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
