# Generated by Django 5.1.1 on 2024-12-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0017_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
