# Generated by Django 5.1.1 on 2024-09-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='wizard',
            options={'verbose_name': 'Волшебник', 'verbose_name_plural': 'Волшебники'},
        ),
        migrations.AddField(
            model_name='wizard',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.guild'),
        ),
    ]
