# Generated by Django 5.1.1 on 2024-09-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0002_guild_alter_wizard_options_wizard_guild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guild',
            options={'verbose_name': 'Гильдия', 'verbose_name_plural': 'Гильдии'},
        ),
        migrations.RemoveField(
            model_name='wizard',
            name='guild_name',
        ),
    ]
