# Generated by Django 5.1.1 on 2024-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0004_customer_order_wizard_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(null=True, upload_to='customers', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='guild',
            name='picture',
            field=models.ImageField(null=True, upload_to='guilds', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='picture',
            field=models.ImageField(null=True, upload_to='wizards', verbose_name='Изображение'),
        ),
    ]
