# Generated by Django 5.1.1 on 2024-11-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0005_customer_picture_guild_picture_wizard_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('completed', 'Выполнен'), ('failed', 'Невыполнен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.guild')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.team'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizards.team'),
        ),
    ]
