# Generated by Django 5.1.1 on 2024-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0014_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='Название'),
        ),
    ]
